#!/bin/bash

echo "Enter your name:"
read name

echo "Enter issue:"
read issue

echo "Choose category:"
echo "1. Hardware"
echo "2. Software"
echo "3. Network"
echo "4. Login"

read category

mkdir -p tickets/hardware
mkdir -p tickets/software
mkdir -p tickets/network
mkdir -p tickets/login

if [ "$category" = "1" ]; then
    FILE="tickets/hardware/hardware.txt"

elif [ "$category" = "2" ]; then
    FILE="tickets/software/software.txt"

elif [ "$category" = "3" ]; then
    FILE="tickets/network/network.txt"

elif [ "$category" = "4" ]; then
    FILE="tickets/login/login.txt"

else
    echo "Invalid category."
    exit
fi

echo "$(date) | $name | $issue" >> $FILE

echo "Ticket saved successfully."
